# AWS credentials profile for the target AWS Account where the solution needs to be deployed
awsProfile: default

# Github parameters
githubOwner: sergei-matheson
repoName: service-workbench-on-aws
repoBranch: mainline

# Email address to receive CodePipeline failure notifications and notifications for manual approval
emailForNotifications: smatheson@dius.com.au
